# Generated by Django 6.0.6 on 2026-06-23 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('barber', 'Barbershop'), ('salon', 'Salon'), ('carwash', 'Car wash'), ('parking', 'Parking')], max_length=20)),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='monitoring.business')),
            ],
            options={
                'unique_together': {('business', 'station_id')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField()),
                ('subject_id', models.CharField(max_length=64)),
                ('is_client', models.BooleanField(null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='monitoring.business')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.station')),
            ],
            options={
                'indexes': [models.Index(fields=['business', 'timestamp'], name='monitoring__busines_68273c_idx'), models.Index(fields=['subject_id'], name='monitoring__subject_dcd94b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=64)),
                ('service', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='monitoring.business')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.station')),
            ],
            options={
                'indexes': [models.Index(fields=['business', 'started_at'], name='monitoring__busines_292c9c_idx')],
            },
        ),
    ]
